style: Address python PEP 8 violations
All violations of the following rules have been resolved and tox/flake8
is no longer set to ignore further violations:

E126: continuation line over-indented for hanging indent
E128: continuation line under-indented for visual indent
E211: whitespace before ‘(‘
E225: missing whitespace around operator
E226: missing whitespace around arithmetic operator
E227: missing whitespace around bitwise or shift operator
E241: multiple spaces after ‘,’
E265: block comment should start with ‘# ‘
E305: expected 2 blank lines after end of function or class
E999: SyntaxError: invalid syntax
F401: <module> imported but unused
F811: redefinition of unused <name> from line <N>
F821: undefined name <name>
F841: local variable <name> is assigned to but never used

The following bashate violation is also addressed:

E006: Line too long

Change-Id: I175779299deba6179b836776e074791ea1425fbe